[package]
name = "ranked-website-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.0.1", default-features = false, features = ["macros"]}
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
reqwest = { version = "0.11.11", features = ["blocking", "json"]}
